"""Initial migration.

Revision ID: 4335e9daad38
Revises:
Create Date: 2025-06-08 18:08:38.398517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4335e9daad38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employees_department', ['department'], unique=False)
        batch_op.create_index('idx_employees_name', ['name'], unique=False)

    op.create_table('hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('exposure_limit', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('safety_measures', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.create_index('idx_hazards_category', ['category'], unique=False)
        batch_op.create_index('idx_hazards_name', ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=False)

    op.create_table('exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('hazard_id', sa.Integer(), nullable=False),
    sa.Column('exposure_level', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exposures', schema=None) as batch_op:
        batch_op.create_index('idx_exposures_date', ['date'], unique=False)
        batch_op.create_index('idx_exposures_employee', ['employee_id'], unique=False)
        batch_op.create_index('idx_exposures_hazard', ['hazard_id'], unique=False)

    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('next_test_date', sa.Date(), nullable=True),
    sa.Column('physician', sa.String(length=100), nullable=True),
    sa.Column('facility', sa.String(length=100), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index('idx_health_records_date', ['date'], unique=False)
        batch_op.create_index('idx_health_records_employee', ['employee_id'], unique=False)
        batch_op.create_index('idx_health_records_test_type', ['test_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index('idx_health_records_test_type')
        batch_op.drop_index('idx_health_records_employee')
        batch_op.drop_index('idx_health_records_date')

    op.drop_table('health_records')
    with op.batch_alter_table('exposures', schema=None) as batch_op:
        batch_op.drop_index('idx_exposures_hazard')
        batch_op.drop_index('idx_exposures_employee')
        batch_op.drop_index('idx_exposures_date')

    op.drop_table('exposures')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_index('idx_hazards_name')
        batch_op.drop_index('idx_hazards_category')

    op.drop_table('hazards')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employees_name')
        batch_op.drop_index('idx_employees_department')

    op.drop_table('employees')
    # ### end Alembic commands ###
